---
- name: Import tsm initial settings with identity store
  ansible.builtin.command:
    cmd: "docker-compose exec -T tableau-server tsm settings import -f /var/opt/tableau-initial_settings.json"
    chdir: "{{ docker_tableau_deploy_dir }}"
  changed_when: True

- name: Apply identity store changes 
  ansible.builtin.command:
    cmd: "docker-compose exec -T tableau-server tsm pending-changes apply --ignore-warnings"
    chdir: "{{ docker_tableau_deploy_dir }}"
  changed_when: True

- name: Run tsm initialize 
  ansible.builtin.command:
    cmd: "docker-compose exec -T tableau-server tsm initialize"
    chdir: "{{ docker_tableau_deploy_dir }}"
  changed_when: True
